import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class StaticService {
  constructor() {}
  AllFood: any = [
    {
      id: 1,
      Dish_Type: 'Indian Cuisines',
      Image: 'assets/image/dishImage/Indian-Cuisine.jpg',
      Desc: 'No vacation is complete without enjoying a wholesome Indian meal. Indian cuisine offers some of the most yummy dishes like Tandoori Chicken, Paneer Butter Masala, Naan bread, and many more.',
      Sub: [
        {
          sub_id: 1,
          sub_category: 'Rice and Roti',
          desc: 'Rice, Polao, Roti, Paratha, Nun, Kulcha',
          imgC: 'assets/image/Indian Category  Dish/rice and roti.webp',
          sub1: [
            {
              Dish_id: 1,
              plate: 'Basanti Polao',
              desc:'A fragrant rice dish along with the goodness of raisins and cashew nuts give a royal touch to this Pulao recipe.',
              imgP: 'assets/image/Indian Category  Dish/Basanti_Pulao.jpg',
              price: 200,
              Rating: '5',
              time:25,
            },
            {
              Dish_id: 2,
              plate: 'Peas Polao',
              desc:'Peas Pulao also known as matar pulao is a classic indian rice pilaf made with basmati rice, whole spices, herbs and of course green peas as they are the star of this dish.',
              imgP: 'assets/image/Indian Category  Dish/Peas-Pulao-Blog.jpg',
              price: 180,
              Rating: '4',
              time:25,
            },
            {
              Dish_id: 3,
              plate: 'Plain Rice',
              desc:"Plain white rice is an excellent inexpensive side dish for nearly any meal—it's hard to find a dish that rice doesn't complement.",
              imgP: 'assets/image/Indian Category  Dish/Plain_rice.jpg',
              price: 90,
              Rating: '4',
              time:25,
            },
            {
              Dish_id: 4,
              plate: 'Jeera Rice',
              desc:'Jeera rice or jeera bhaat [1] is an Indian dish consisting of rice and cumin seeds.',
              imgP: 'assets/image/Indian Category  Dish/Jeera-Rice-small.webp',
              price: 120,
              Rating: '4',
              time:25,
            },
            {
              Dish_id: 5,
              plate: 'Tandori Roti(Per Piece)',
              desc:'With crisp edges, a soft interior, and a chewy texture, this whole wheat roti recipe is perfect for serving with any kind of Punjabi food, especially rich curry dishes.',
              imgP: 'assets/image/Indian Category  Dish/Tandori Roti.webp',
              price: 20,
              Rating: '5',
              time:25,
            },
            {
              Dish_id: 6,
              plate: 'Paratha(Per Piece)',
              desc:'Golden-brown in color, flaky and layered, paratha is a type of Indian bread that is typically consumed for breakfast.',
              imgP: 'assets/image/Indian Category  Dish/paratha.jpg',
              price: 15,
              Rating: '4',
              time:25,
            },
            {
              Dish_id: 7,
              plate: 'Rumali Roti(Per Piece)',
              desc:'Rumali is usually made with a combination of whole wheat atta flour and white wheaten maida flour and cooked on the convex side of a karahi.',
              imgP: 'assets/image/Indian Category  Dish/roomali-roti_620x350_71499078720.jpg',
              price: 15,
              Rating: '4',
              time:25,
            },
            {
              Dish_id: 8,
              plate: 'Butter Nun(Per Piece)',
              desc:'Butter Naan is a leavened flatbread mostly cooked in a tandoor(clay oven).It is one of the most ordered flatbreads in Indian restaurants & is eaten with a curry or dal',
              imgP: 'assets/image/Indian Category  Dish/butter-naan.webp',
              price: 50,
              Rating: '4',
              time:25,
            },
            {
              Dish_id: 9,
              plate: 'Masala Kulcha(per piece)',
              desc:'Masala kulcha is actually a kind of Indian bread recipe blended with a range of spices and a stuffing. This is actually a North Indian recipe that is usually served with pickles or some other side dish. A masala kulcha is stuffed with potatoes, spices and onions.',
              imgP: 'assets/image/Indian Category  Dish/kulcha.webp',
              price: 60,
              Rating: '4.9',
              time:25,
            },
            {
              Dish_id: 10,
              plate: 'Lachcha Paratha (Per Piece)',
              desc:"Laccha Paratha is a popular variant of paratha from North Indian cuisine. These are whole wheat flatbreads made with a simple unleavened dough consisting of basic ingredients like whole wheat flour, salt and ghee or oil.",
              imgP: 'assets/image/Indian Category  Dish/Lachha-Paratha.jpg',
              price: 30,
              Rating: '5',
              time:25,
            },
          ],
        },
        {
          sub_id: 2,
          sub_category: 'Veg Side Dish',
          desc: 'Mixed, Paneer, Sukto, Dhoka, Alu Posto, Mocha',
          imgC: 'assets/image/Indian Category  Dish/veg-side-dish.jpg',
          sub1: [
            {
              Dish_id: 1,
              plate: 'Bori Die Suktoni',
              desc:'Shukto / Sukto is a traditional bengali recipe.A recipe is a nice story that finishes with a delicious meal. This is cooked with various veggies and we mostly stsrts traditional Bengali meal with rice and shuktoni.',
              imgP: 'assets/image/Indian Category  Dish/sukto.webp',
              price: 60,
              Rating: '5',
              time:30,
            },
            {
              Dish_id: 2,
              plate: 'Allu Posto',
              desc:'Alu posto is a classic Bengali dish. Sparing in its use of spices, this preparation relies on the flavours of potatoes, green chillies and nigella seeds for its taste. What stands out, however, is the nutty flavour of the roasted poppy paste, which also provides body and texture to the gravy.',
              imgP: 'assets/image/Indian Category  Dish/alu-posto.jpg',
              price: 70,
              Rating: '4.8',
              time:30,
            },
            {
              Dish_id: 3,
              plate: 'Mochar Ghonto',
              desc:"Mochar Ghonto is a dry curry recipe and is often served along with steaming hot rice and ghee.'Mocha' in Bengali means Plantain flowers or Banana blossoms. Plantain Flowers have amazing health benefits. They are high source of vitamins and minerals and also helps to prevent infections.",
              imgP: 'assets/image/Indian Category  Dish/mocharghonto.jpg',
              price: 40,
              Rating: '4.7',
              time:30,
            },
            {
              Dish_id: 4,
              plate: 'Dhokar Dalna',
              desc:"A Bengali vegetarian classic of fried lentil cakes, finished in a warm, spicy, ginger-and-cumin laced sauce. Dhoka'r dalna is a typical Bengali niramish (without onion and garlic) delicacy.",
              imgP: 'assets/image/Indian Category  Dish/dhoka.jpg',
              price: 65,
              Rating: '4.6',
              time:30,
            },
            {
              Dish_id: 5,
              plate: 'Panch Mishali Torkari',
              desc:"Panch Mishali Tarkari is a Bengali Mix-veg prepared with several veggies and tempered with Panch Phoron. Panch Mishali Tarkari calls for only Panch Phoran and little Ginger Paste and obviously several veggie, like Potato, Pumpkin, Radish, Broad Beans and Eggplant. What I add separately is a powder of Panch Phoron.",
              imgP: 'assets/image/Indian Category  Dish/Mix-Veg.webp',
              price: 50,
              Rating: '4.0',
              time:30,
            },
            {
              Dish_id: 6,
              plate: 'Paneer Butter Masala',
              desc:"Paneer butter masala also known as butter paneer is a rich & creamy curry made with paneer,spices,onions,tomatoes,cashews and butter. The curry is cooked in butter which imparts it's characteristic buttery flavour to the dish",
              imgP: 'assets/image/Indian Category  Dish/Paneer-butter-masala.jpg',
              price: 200,
              Rating: '4.8',
              time:30,
            },
            {
              Dish_id: 7,
              plate: 'Palang Paneer',
              desc:"Palak Paneer is a popular Indian Vegetarian Dish consisting of paneer in a smooth, creamy and delicious spinach gravy. This is simply delicious, rich,absolutely flavorsome & tastes better than in any restaurant.",
              imgP: 'assets/image/Indian Category  Dish/palak-paneer.jpg',
              price: 150,
              Rating: '4.7',
              time:30,
            },
            {
              Dish_id: 8,
              plate: 'Matar Paneer',
              desc:"Matar paneer recipe is a popular Indian Curry dish made with green peas and Paneer (Indian cottage cheese) in a base of onions, tomatoes, cashews, spices and herbs. The recipe hails from the versatile Northern Indian cuisine that has many different (and delicious) variations.",
              imgP: 'assets/image/Indian Category  Dish/Matar-Paneer.jpg',
              price: 150,
              Rating: '4.2',
              time:30,
            },
            {
              Dish_id: 9,
              plate: 'Paneer  Lababdar',
              desc:"Paneer Lababdar is an easy-to-prepare, restaurant-style dish of paneer (Indian cottage cheese) in a creamy, mildly tangy and faintly sweet gravy. Onions, tomatoes, cashews and spices make this a rich, flavorful and delicious recipe. This vegetarian Paneer Lababdar recipe is also naturally gluten-free.",
              imgP: 'assets/image/Indian Category  Dish/paneer-lababdar-1.jpg',
              price: 170,
              Rating: '4.3',
              time:30,
            },
            {
              Dish_id: 10,
              plate: 'Sahee Paneer',
              desc:"Shahi Paneer is a succulent Indian dish of soft, pillowy paneer floating in a creamy gravy. This dish made with Indian cottage cheese simmered in an onion-nut paste,and enriched with yogurt and mild spices,is a throwback to the era of kings and royal kithens.",
              imgP: 'assets/image/Indian Category  Dish/shahi-paneer-2.webp',
              price: 200,
              Rating: '4.0',
              time:30,
            },
          ],
        },
        {
          sub_id: 3,
          sub_category: 'Non Veg Side Dish',
          desc: 'Prawn, Fish, Chicken, Mutton',
          imgC: 'assets/image/Indian Category  Dish/Non Veg Side Dish.jpg',
          sub1: [
            {
              Dish_id: 1,
              plate: 'Lau Chingri',
              desc:"Lau Chingri is bottle gourd cooked with shrimps, a delicacy from West Bengal. I love authentic Bengali cuisine, most of the recipes are so simple with minimal ingredients, yet so flavourful. It’s the same with Lau chingri, the humble bottle gourd gets a complete makeover by the use of shrimps.",
              imgP: 'assets/image/Indian Category  Dish/Lau-Chingri.jpg',
              price: 65,
              Rating: '4.3',
              time:20,
            },
            {
              Dish_id: 2,
              plate: 'Vetki Pathuri',
              desc:"Bhetki paturi is a traditional preparation of Bhetki or barramundi fish, where basically well-marinated boneless vetki or bhetki fillets are wrapped up in banana leaf for making this recipe either by slow cooking in a greased pan or steamed up.",
              imgP: 'assets/image/Indian Category  Dish/vetki pathuri.jpg',
              price: 180,
              Rating: '4.7',
              time:20,
            },
            {
              Dish_id: 3,
              plate: 'Ilish Bhaapa',
              desc:"This is a dish for you if you love the punch of the mustard. Extremely soft, melt-in-the-mouth, buttery fish fillets cooked without effort.The fish has a buttery texture and melts in your mouth immediately.",
              imgP: 'assets/image/Indian Category  Dish/Ilish-Bhapa.jpg',
              price: 280,
              Rating: '4.5',
              time:20,
            },
            {
              Dish_id: 4,
              plate: 'Chingri Macher Malaikari',
              desc:"Chingri macher malai curry is an exemplary fish curry recipe which is crazily popular among Bengalis. It is renowned for its inimitable taste, texture and flavour. In this preparation, large tiger prawns (bagda chingri or golda chingri) are cooked in coconut milk with onion, tomato and a few fragrant Bengali spices.",
              imgP: 'assets/image/Indian Category  Dish/prawn malaikari.jpg',
              price: 250,
              Rating: '4.9',
              time:20,
            },
            {
              Dish_id: 5,
              plate: 'Chicken 65',
              desc:"Chicken 65 is a spicy chicken dish from South India. It consists of fried chicken that is sautéed in a bright red sauce made with yoghurt and chilli peppers. It is usually served with onions and lemons.",
              imgP: 'assets/image/Indian Category  Dish/chicken 65.jpg',
              price: 180,
              Rating: '4.6',
              time:20,
            },
            {
              Dish_id: 6,
              plate: 'Chicken Curry',
              desc:"A typical curry from the Indian subcontinent consists of chicken stewed in an onion - and tomato -based sauce, flavoured with ginger, garlic, tomato puree, chilli peppers and a variety of spices, often including turmeric, cumin, coriander, cinnamon, and cardamom.",
              imgP: 'assets/image/Indian Category  Dish/chicken curry.jpg',
              price: 150,
              Rating: '4.1',
              time:20,
            },
            {
              Dish_id: 7,
              plate: 'Achari Chicken',
              desc:"Also known as Achari Murgh, a popular dish from Mughlai cuisine and can be served with buttered naan, roti, rice. Grind coarsely the whole seeds mixture and keep aside.Achari chicken is best eaten during the cold winters as it is the right time to enjoy spicy and hot foods. Many people love to add a bit of pickle to any achari dish.",
              imgP: 'assets/image/Indian Category  Dish/achari chicken.jpg',
              price: 200,
              Rating: '4.4',
              time:20,
            },
            {
              Dish_id: 8,
              plate: 'Chicken Butter Masala',
              desc:"A creamy yet spicy chicken dish that resonates with any restaurant style chicken dish and gives an irresistible aroma of spices. A buttery chicken curry cooked with tangy tomatoes and cream. This is what we call pure pleasure.",
              imgP: 'assets/image/Indian Category  Dish/chicken butter mashala.jpg',
              price: 240,
              Rating: '4.2',
              time:20,
            },
            {
              Dish_id: 9,
              plate: 'Mutton Kasha',
              desc:"Mutton kasha is a yummy spicy Bengali-style cooking of goat meat. Full of raw flavors of crushed spices, curd, and mustard oil, the traditional style mutton kosha gravy recipe is a favorite cuisine in every bong household.",
              imgP: 'assets/image/Indian Category  Dish/mutton kosha.webp',
              price: 300,
              Rating: '4.3',
              time:20,
            },
            {
              Dish_id: 10,
              plate: 'Mutton Duckbanglo',
              desc:"Mutton Dak Bungalow is a culinary treasure that survives among a few remaining khansama families and Anglo Indian households. It is always cooked along with Potato, Egg and freshly ground spices. You can serve it along with Phulka and jeera pulao to make your sunday lunch special.",
              imgP: 'assets/image/Indian Category  Dish/mutton-dak-bungalow.jpg',
              price: 350,
              Rating: '4.6',
              time:20,
            },
          ],
        },
      ],
    },
    {
      id: 2,
      Dish_Type: 'Chinese Cuisine',
      Image: 'assets/image/dishImage/Chinese-Cuisine.jpg',
      Desc: 'Chinese cuisine is as diverse as their culture where every region writes up a new menu. Cooking styles, ingredients, flavours - all differ from region to region.',
      Sub: [
        {
          sub_id: 1,
          sub_category: 'Soups',
          desc: 'Corn, Chicken, Mushroom, Sesame, Seafood, Mutton, Noodle, Crab',
          imgC: 'assets/image/Chinese Cuisine/soup.png',
          sub1: [
            {
              Dish_id: 1,
              plate: 'Sweet Corn Non Veg Soup',
              desc:"Sweet corn soup made with tender corn kernels,spices and herbs. This dish is made in several cultures acroos the world",
              imgP: 'assets/image/Chinese Cuisine/chicken_sweetcorn soup.jpg',
              price: 180,
              Rating: '4.6',
              time:20,
            },
            {
              Dish_id: 2,
              plate: 'Hot And Sour Soup',
              desc:"The Chinese hot and sour soup is usually meat-based, and often contains ingredients such as day lily buds, wood ear fungus, bamboo shoots, and tofu, in a broth that is sometimes flavored with pork blood. Sometimes, the soup would also have carrots and pieces of pork.",
              imgP: 'assets/image/Chinese Cuisine/veg-hot-and-sour-soup-1.jpg',
              price: 110,
              Rating: '4.4',
              time:20,
            },
            {
              Dish_id: 3,
              plate: 'Chicken Clear Soup',
              desc:"Chicken Clear Soup is made by simmering veggies, & or meat in a liquid until all the flavours are released. this soup is made without the addition of any spices,starch or any other flavoring ingredients. This soup tastes awesome when served piping hot with some noodles or fried rice.",
              imgP: 'assets/image/Chinese Cuisine/chicken clear soup.jpg',
              price: 160,
              Rating: '4.5',
              time:20,
            },
            {
              Dish_id: 4,
              plate: 'Mushroom Soup',
              desc:"Rich and delicious mushroom soup is wonderfully satisfying to enjoy any time of the year.This naturally vegetarian dish is hearty, rich, and full of deep umami flavor. It’s great topped with fresh herbs and served as a side or main dish!",
              imgP: 'assets/image/Chinese Cuisine/mushroom soup.jpg',
              price: 100,
              Rating: '4.1',
              time:20,
            },
            {
              Dish_id: 5,
              plate: 'Schewajan Soup',
              desc:"Amazing Schezwan Soup to warm up your evenings. This appetizing soup is prepared with just a few basic ingredients and tastes oh-so-good. Despite the name 'Szechuan', it doesn't feature any numbing spiciness but leans towards a salty & sour taste profile.",
              imgP: 'assets/image/Chinese Cuisine/schewajan_soup.jpg',
              price: 120,
              Rating: '4.6',
              time:20,
            },
            {
              Dish_id: 6,
              plate: 'Black Sesame Soup',
              desc:"Black sesame soup or paste is a popular Chinese sweet soup made from black sesame seeds and rice. This nutty, fragrant, and healthy soup is the perfect ending to a meal. The consistency can be thick (like a pudding) or thin (more watery) depending on preference.",
              imgP: 'assets/image/Chinese Cuisine/black-sesame-soup.jfif',
              price: 135,
              Rating: '4.2',
              time:20,
            },
            {
              Dish_id: 7,
              plate: 'Cantonese Seafood Soup',
              desc:"Cantonese seafood soup is one of the main seafood soups within Cantonese cuisine. It is commonly found in Hong Kong, and is also available in Chinatowns in other nations. The soup is usually considered midrange to high-end in price depending on the ingredients.",
              imgP: 'assetsimageChinese Cuisinecantonese_seafood_soup.jpg',
              price: 210,
              Rating: '4.5',
              time:20,
            },
            {
              Dish_id: 8,
              plate: 'Boiled Mutton Soup',
              desc:"Mutton soup made using mutton bones is a healthy recipe for winters with a liquid and hot texture. The healthy non-veg soup keeps the body temperature warm. This soup is good to drink in the mornings, at lunch, and at dinners.",
              imgP: 'assets/image/Chinese Cuisine/cantonese_seafood_soup.jpg',
              price: 240,
              Rating: '4.7',
              time:20,
            },
            {
              Dish_id: 9,
              plate: 'Noodle Soup',
              desc:"Chinese noodle soups are traditionally made with thin egg noodles (pictured above, and below in the soup). Fresh ones (sold in the fridge section) have a better texture than dried.",
              imgP: 'assets/image/Chinese Cuisine/Noodle-Soup.jpg',
              price: 150,
              Rating: '4.3',
              time:20,
            },
            {
              Dish_id: 10,
              plate: 'Corn Crab Soup',
              desc:"This crab and corn soup or corn crab soup is a Chinese soup dish that serves in most Chinese Restaurants. The creamy corn crab soup (with milk or cream) can be found in Chinese-Canadian Cuisine and Chinese-American Cuisine.",
              imgP: 'assets/image/Chinese Cuisine/CornCrab_soup.jpg',
              price: 200,
              Rating: '4.4',
              time:20,
            },
          ],
        },
        {
          sub_id: 2,
          sub_category: 'Momo',
          desc: 'Veg, Chicken, Nonveg, Paneer',
          imgC: 'assets/image/Chinese Cuisine/Wow-Momo.webp',
          sub1: [
            {
              Dish_id: 1,
              plate: 'Tandoori Momo',
              desc:"A fusion of authentic nepali momos recipe with our own popular punjabi cuisine with tandoori gravy. savoury dumplings are always good to party starters or snacks but tandoori based momos make it even more flavorful.",
              imgP: 'assets/image/Chinese Cuisine/tandoori_momo.jpg',
              price: 150,
              Rating: '4.4',
              time:25,
            },
            {
              Dish_id: 2,
              plate: 'Chocolate Momo',
              desc:"The most recent and gourmet momo food trend is to stuff up that dough with chocolate. Whether you have them steamed or fried is immaterial, as long as you make sure that you've tried chocolate momos at least once.",
              imgP: 'assets/image/Chinese Cuisine/chocolate_momo.webp',
              price: 120,
              Rating: '4.6',
              time:25,
            },
            {
              Dish_id: 3,
              plate: 'Veg Momo',
              desc:"Momo are bite-size dumplings made with a spoonful of stuffing wrapped in dough with origins from Nepal. Momo are usually steamed, though they are sometimes fried or steam-fried. Meat or vegetables fillings becomes succulent as it produces an intensively flavored broth sealed inside the wrappers.",
              imgP: 'assets/image/Chinese Cuisine/veg-momos.webp',
              price: 90,
              Rating: '4.3',
              time:25,
            },
            {
              Dish_id: 4,
              plate: 'Chicken Panfried Momo',
              desc:"Chicken Pan Fried Momos is one of the delicious spicy Momo recipe. Momo is very popular food of Tibet, Nepal, Bhutan and Sikkim. It is also known as Dumplings or Dim Sum.",
              imgP: 'assets/image/Chinese Cuisine/ChickenPanFired_Momo.webp',
              price: 110,
              Rating: '4.2',
              time:25,
            },
            {
              Dish_id: 5,
              plate: 'Mozerella Cheese Momo',
              desc:"The dough of the momo is stuffed with either Paneer, Khuwa or Cheese and is served with achar. Although, it sounds a bit unusual, consuming dairy product in the form of momo is always an option.",
              imgP: 'assets/image/Chinese Cuisine/cheese momo.jfif',
              price: 120,
              Rating: '4.0',
              time:25,
            },
            {
              Dish_id: 6,
              plate: 'Non Veg Momo',
              desc:"Chicken Momos Recipe is a delicious and simple momos recipe filled with juicy minced chicken. A street food special found mostly in Darjeeling or Sikkim. The fillings for these momos are quite simple and light. Serve this momos along with chilli garlic sauce.",
              imgP: 'assets/image/Chinese Cuisine/Chicken-Momos.jpg',
              price: 100,
              Rating: '4.1',
              time:25,
            },
            {
              Dish_id: 7,
              plate: 'Momos In Chilly Garlic Sauce',
              desc:"Spicy and sweet filled with garlic flavour this momos taste amazing on its own as an Appetizer. It has lots of veggies added in them which makes it more tasty and healthy.",
              imgP: 'assets/image/Chinese Cuisine/Chilly garlic sauce momo.webp',
              price: 120,
              Rating: '4.9',
              time:25,
            },
            {
              Dish_id: 8,
              plate: 'Afgani Malai Momo',
              desc:"Afghani Malai Momos are luscious, creamy, drizzled and cooked with whisked curd, fresh cream, cheese, cilantro and freshly ground spices.",
              imgP: 'assets/image/Chinese Cuisine/afgani_malai_momo.webp',
              price: 140,
              Rating: '4.8',
              time:25,
            },
            {
              Dish_id: 9,
              plate: 'Schezuan Momo',
              desc:"Schezwan Paneer Momos are filled with paneer and vegetables and tossed in a spicy homemade schezwan sauce. These vegetarian dumplings are so good on their own or with a side of spicy chutney.",
              imgP: 'assets/image/Chinese Cuisine/Schewajan_momo.jpg',
              price: 130,
              Rating: '4.7',
              time:25,
            },
            {
              Dish_id: 10,
              plate: 'Paneer Momo',
              desc:"an indian version of nepali momos recipe made with grated and spiced paneer. it is a great party starter or appetiser which can be served just before the meal or can also be served as evening snacks.",
              imgP: 'assets/image/Chinese Cuisine/paneer momo.webp',
              price: 110,
              Rating: '4.7',
              time:25,
            },
          ],
        },
        {
          sub_id: 3,
          sub_category: 'Rice And Noodles',
          desc: 'Chicken, Veg, Egg, Mixed, Cantonese',
          imgC: 'assets/image/Chinese Cuisine/rice & noddles.jpg',
          sub1: [
            {
              Dish_id: 1,
              plate: 'Chicken Fried Rice',
              desc:"Chicken fried rice is the comfort dish of Chinese food. It's been around for a very long time and is also common in East, Southeast, and South Asian cuisines.",
              imgP: 'assets/image/Chinese Cuisine/chicken-fried-rice.jpg',
              price: 200,
              Rating: '4.3',
              time:30,
            },
            {
              Dish_id: 2,
              plate: 'Veg Fried Rice',
              desc:"This classic Veg Fried Rice recipe is made with a hearty mix of fresh vegetables, green onions, seasonings and spices for an incredibly flavorful fried rice dish.",
              imgP: 'assets/image/Chinese Cuisine/veg fried rice.jpg',
              price: 130,
              Rating: '4.2',
              time:30,
            },
            {
              Dish_id: 3,
              plate: 'Egg Fried Rice',
              desc:"Fluffy and aromatic egg fried rice is a crowd pleaser. A hearty meal on the go and a satisfying dinner after a hard day at work.",
              imgP: 'assets/image/Chinese Cuisine/Egg-Fried-Rice.jpg',
              price: 140,
              Rating: '4.1',
              time:30,
            },
            {
              Dish_id: 4,
              plate: 'Mixed Fried Rice',
              desc:"A little bit of everything comes together so well in this mixed fried rice made with chicken, prawns, eggs and veggies. Any of your favourite veggies can be used to make this Asian style mixed fried rice.",
              imgP: 'assets/image/Chinese Cuisine/mixed_fried_Rice.webp',
              price: 240,
              Rating: '4.6',
              time:30,
            },
            {
              Dish_id: 5,
              plate: 'Chicken Chowmin',
              desc:"Chicken chowmein refers to a stir-fried noodle dish made with pieces of chicken. The term 'chowmein' is Chinese for 'fried noodles', and chow mein noodles can either be soft or crunchy.",
              imgP: 'assets/image/Chinese Cuisine/chicken-chow-mein.jpg',
              price: 200,
              Rating: '5.0',
              time:30,
            },
            {
              Dish_id: 6,
              plate: 'Veg Chowmin',
              desc:"veg chow mein is basically stir fried noodles with lots of veggies. smooth velvety noodles with crunch from the veggies. it is utterly slurp-able to the last bite.",
              imgP: 'assets/image/Chinese Cuisine/vegetable-chow-mein.jpg',
              price: 110,
              Rating: '4.9',
              time:30,
            },
            {
              Dish_id: 7,
              plate: 'Egg Chowmin',
              desc:"Filling and full of flavours, this egg chowmein recipe is filled with eggs, sauces and desi spices which make it a super wholesome treat.",
              imgP: 'assets/image/Chinese Cuisine/egg_chowmin.webp',
              price: 110,
              Rating: '4.8',
              time:30,
            },
            {
              Dish_id: 8,
              plate: 'Mixed Chowmin',
              desc:"Mixed Chowmein is a versatile Chinese recipe that is a complete meal in itself. It is a lip-smacking recipe that is ideal for lunch, dinner and even snacks. The best part about Mixed Chowmein is that it contains a lot of vegetables which makes the dish healthy.",
              imgP: 'assets/image/Chinese Cuisine/mixed chowmin.jpg',
              price: 230,
              Rating: '4.7',
              time:30,
            },
            {
              Dish_id: 9,
              plate: 'Lemon Fried Rice',
              desc:"This appealing blend of rice and veggies complements most meats. The lemon peel and hot sauce transform regular fried rice into a distinctive side dish.",
              imgP: 'assets/image/Chinese Cuisine/lemon_fried_rice.jpg',
              price: 160,
              Rating: '4.5',
              time:30,
            },
            {
              Dish_id: 10,
              plate: 'Cantonese Rice Noodles',
              desc:"These Cantonese pan fried noodles are popular in Hong Kong. They are crispy, chewy, and packed with smoky yet savory flavor. You can customize this versatile noodle dish with pretty much anything you feel like adding.",
              imgP: 'assets/image/Chinese Cuisine/Cantonese_rice_noodles.jpg',
              price: 180,
              Rating: '4.6',
              time:30,
            },
          ],
        },
        {
          sub_id: 4,
          sub_category: 'Chinese Side Dish',
          desc: 'Chicken, Mushroom, Paneer',
          imgC: 'assets/image/Chinese Cuisine/chinese_side_dish.webp',
          sub1: [
            {
              Dish_id: 1,
              plate: 'Chilli Chicken',
              desc:"Chilli chicken is a sweet, spicy & slightly sour crispy appetizer made with chicken, bell peppers, garlic, chilli sauce & soya sauce. It is best served hot as an appetizer or with any tyoe of fried rice.",
              imgP: 'assets/image/Chinese Cuisine/chilli_chicken.webp',
              price: 220,
              Rating: '4.4',
              time:40,
            },
            {
              Dish_id: 2,
              plate: 'Kung Pao Chicken',
              desc:"Kung pao chicken is Chinese-style stir-fried chicken cubes with dried chili peppers. It’s a Sichuanese staple that was brought over to America and reinvented for local flavors and tastes.",
              imgP: 'assets/image/Chinese Cuisine/kung_pao_chicken.jpg',
              price: 240,
              Rating: '4.2',
              time:40,
            },
            {
              Dish_id: 3,
              plate: 'Schewajan Chicken',
              desc:"Schezwan Chicken Schezwan Chicken also known as Szechuan chicken or Sichuan chicken is a Chinese style chicken appetizer popular on the Chinese restaurant menus & takeaways. Schezwan chicken is crisp fried chicken tossed in a spicy, sour, hot & tongue tickling Sichuan sauce.",
              imgP: 'assets/image/Chinese Cuisine/szechuan-chicken.jpg',
              price: 240,
              Rating: '4.1',
              time:40,
            },
            {
              Dish_id: 4,
              plate: 'Lemon Chicken',
              desc:"This Lemon chicken recipe yields tender chicken bites with a dominant flavour of lemon juice, mint and mild spices. Slightly tangy, mildly hot with full of flavours. It makes a great starter for parties or get together and can also be served as a side to a main course.",
              imgP: 'assets/image/Chinese Cuisine/lemon_chicken.jfif',
              price: 230,
              Rating: '4',
              time:40,
            },
            {
              Dish_id: 5,
              plate: 'Mushroom Manchurian (Dry) ',
              desc:"Mushrooms coated in flour are crisp and crunchy. With a simple sauce made with soy sauce, salt, sugar, pepper powder, garlic and chillies, the crispness is retained while adding a lot of bursting flavors. This recipe for low calorie mushroom manchurian dry is a keeper and replace the veggie with anything of your choice.",
              imgP: 'assets/image/Chinese Cuisine/Mushroom-Manchurian (1).jpg',
              price: 190,
              Rating: '4.5',
              time:40,
            },
            {
              Dish_id: 6,
              plate: 'Paneer Manchurian',
              desc:"Paneer Manchurian is a savory, satisfying dish that features (shallow or deep) fried paneer cubes. This Indo-Chinese fusion Paneer Manchurian recipe can be prepared either dry with a light sweet, salty, and tangy sauce. Or, make a saucy version with a heavier gravy that’s perfect to enjoy over fried rice.",
              imgP: 'assets/image/Chinese Cuisine/Paneer-Manchurian-dry-.jpg',
              price: 220,
              Rating: '4.2',
              time:40,
            },
            {
              Dish_id: 7,
              plate: 'Chilli Paneer (Dry)',
              desc:"Chilli Paneer is one of the popular vegetarian appetizers served in the Indian-Chinese restaurants. This recipe with options to prepare dry, semi dry & gravy versions.",
              imgP: 'assets/image/Chinese Cuisine/Chilli-Paneer.jpg',
              price: 210,
              Rating: '4.9',
              time:40,
            },
            {
              Dish_id: 8,
              plate: 'Garlic Chicken',
              desc:"This Chinese Garlic Chicken makes a great easy weeknight dinner. A total breeze to make! This full-of-flavor garlic chicken makes not only an awesome quick & easy weeknight dinner but is also a really great party food! ",
              imgP: 'assets/image/Chinese Cuisine/Garlic-Chicken.webp',
              price: 230,
              Rating: '4.3',
              time:40,
            },
            {
              Dish_id: 9,
              plate: 'Chicken Chop Suey',
              desc:"Chop Suey is just a slightly westernised version of a classic, basic Chinese stir fry. Because of this, there really aren’t hard and fast rules about what goes in it, but the general characteristic is that the sauce is a fairly light brown colour, there is plenty of it (and you know I love my sauce!!) and it’s pretty thick so it clings to your rice or noodles.",
              imgP: 'assets/image/Chinese Cuisine/chicken-chop-suey.jpg',
              price: 230,
              Rating: '4.7',
              time:40,
            },
            {
              Dish_id: 10,
              plate: 'Peri Peri Chicken',
              desc:"Piri piri Chicken is grilled chicken that has been marinated in that spicy chili piri piri sauce – though some grill the chicken first, then simply baste the sauce on at the end. It’s super popular with people sticking to a paleo diet.",
              imgP: 'assets/image/Chinese Cuisine/peri-peri-chicken.jpg',
              price: 240,
              Rating: '4.5',
              time:40,
            },
          ],
        },
      ],
    },
    {
      id: 3,
      Dish_Type: 'Desserts',
      Image: 'assets/image/dishImage/Dessert.png',
      Desc: "Dessert is the cherry on top of a perfect meal.",
      Sub: [
        {
          sub_id: 1,
          sub_category: 'Sweets',
          desc: '10 Types',
          imgC: 'assets/image/dishImage/Desserts.png',
          sub1: [
            {
              Dish_id: 1,
              plate: 'Rosogolla',
              desc:"Rasgulla is a traditional sweet that is usually served at the end of a meal, like many other Indian milk-based desserts. It is prepared from chhena paneer dumplings and semolina dough, cooked together in a sugary syrup.",
              imgP: 'assets/image/desserts/rasgulla.jpeg',
              price: 15,
              Rating: '4.2',
              time:0,
            },
            {
              Dish_id: 2,
              plate: 'Gulab Jamun',
              desc:"Gulab jamun is a dessert based on milk solids that are kneaded into a dough, shaped into balls, and deep-fried in ghee. The balls then get soaked in a sugary concoction flavored with saffron, green cardamom, and rose water.",
              imgP: 'assets/image/desserts/gulab-jamuns.jpg',
              price: 20,
              Rating: '4.5',
              time:0,
            },
            {
              Dish_id: 3,
              plate: 'Baked Rosogolla(Per Piece)',
              desc:"Baked Rosogolla is a delicious and easy twist to the classic Bengali Rosogollar Paayesh where the Rasgullas(Rosogolla) are baked/broiled in a thick caramelized sweet milk.",
              imgP: 'assets/image/desserts/Baked-rosogolla.webp',
              price: 25,
              Rating: '5',
              time:0,
            },
            {
              Dish_id: 4,
              plate: 'Mihidana(Per Kg)',
              desc:"Mihidana is an Indian sweet from Burdwan, West Bengal, India. Mihidana, described as the micro cousin of the traditional Boondi, is derived from two words, Mihi meaning fine, and Dana, meaning grain.",
              imgP: 'assets/image/desserts/mihidana.jpg',
              price: 250,
              Rating: '4.1',
              time:0,
            },
            {
              Dish_id: 5,
              plate: 'Pathishapta',
              desc:"Patishapta are thin crepes or pancakes made with refined flour, rice flour and semolina stuffed with a delicious caramelized shredded coconut filling.",
              imgP: 'assets/image/desserts/patisapta.jpg',
              price: 20,
              Rating: '4.3',
              time:0,
            },
            {
              Dish_id: 6,
              plate: 'Khirkodom',
              desc:"An exotic Bengali sweet what an exotic sweet Kheer-kadam, otherwise known as Raskadam, is enclosing another one. It's a kind of sweet, where a sweet is covered by a layer, turning it completely into a new kind.",
              imgP: 'assets/image/desserts/KheerKodam.webp',
              price: 16,
              Rating: '4',
              time:0,
            },
            {
              Dish_id: 7,
              plate: 'Komola Bhog',
              desc:"Kamola vog is a signature Bengali orange-flavored sweet prepared with Chana ,similar to rashogolla. It needed orange flavoring and also color along with the ingredients of Rajbhog.",
              imgP: 'assets/image/desserts/kamala_vog.webp',
              price: 20,
              Rating: '4',
              time:0,
            },
            {
              Dish_id: 8,
              plate: 'Ghee Jalebi(Per Kg)',
              desc:"Jalebi is one of the most common and popular desserts from Indian subcontinent. iiiiiit is a spiral shaped crisp & juicy sweet made with all-purpose flour,gram flour and sugar syrup.",
              imgP: 'assets/image/desserts/ghee-Jalebi.jpg',
              price: 300,
              Rating: '4.6',
              time:0,
            },
            {
              Dish_id: 9,
              plate: 'Roso Malai',
              desc:"Rasomalai is a popular East Indian delicacy made with milk,a curdling agent, sugar, nuts, saffron and cardamoms.",
              imgP: 'assets/image/desserts/Rasmalai.jpg',
              price: 30,
              Rating: '4.5',
              time:0,
            },
            {
              Dish_id: 10,
              plate: 'Kaju Barfi(Per Kg)',
              desc:"A delectable blend of cashew nut and milk, topped by silver leaf, traditionally served at festivals like Diwali and other special occasions.",
              imgP: 'assets/image/desserts/kaju burfi.webp',
              price: 400,
              Rating: '5',
              time:0,
            },
          ],
        },
        {
          sub_id: 2,
          sub_category: 'Ice Cream',
          desc: 'Ten Types',
          imgC: 'assets/image/desserts/Ice-cream.png',
          sub1: [
            {
              Dish_id: 1,
              plate: 'Magnum Almond Ice Cream',
              desc:"Velvety smooth vanilla ice cream covered in thick cracking belgian chocolate and almond pieces.",
              imgP: 'assets/image/desserts/magnum-almond-ice-cream.webp',
              price: 200,
              Rating: '4.8',
              time:0,
            },
            {
              Dish_id: 2,
              plate: 'Cookies and Cream Ice Cream',
              desc:"Cookies and cream is a variety of ice cream, milkshake and other desserts that includes chocolate sandwich cookies.",
              imgP: 'assets/image/desserts/cookies-and-cream-ice-cream.jpg',
              price: 180,
              Rating: '4.8',
              time:0,
            },
            {
              Dish_id: 3,
              plate: 'Belgium Choclate Ice Cream',
              desc:"Dark Chocolaty Belgian Chocolate Ice Cream topped with chocolate shavings and chocolate chips is a true delight in itself.",
              imgP: 'assets/image/desserts/Belgian-Chocolate.jpg',
              price: 300,
              Rating: '4.3',
              time:0,
            },
            {
              Dish_id: 4,
              plate: 'Sea Salt Ice Cream',
              desc:"Sea salt ice cream is ice cream flavored with salt. While there are some commercial versions available, it is not always an easy flavor to find, so making it at home may be the best option.",
              imgP: 'assets/image/desserts/sea_salt.jpg',
              price: 300,
              Rating: '4.5',
              time:0,
            },
            {
              Dish_id: 5,
              plate: 'Black Forest Feast',
              desc:"It's a decadent mix of rich chocolate ice cream with a tangy cherry swirl and flakes of dark chocolate. This ice cream is philly style so there are no eggs and no custard.",
              imgP: 'assets/image/desserts/fruit_n_nut_feast.webp',
              price: 280,
              Rating: '4.7',
              time:0,
            },
            {
              Dish_id: 6,
              plate: 'Gulab Jamun Ice Cream',
              desc:"Gulab jamun Ice Cream is a special desi flavour ice cream which got its recipe as many love to eat Ice cream with Gulab jamun.",
              imgP: 'assets/image/desserts/gulab_jamun_ice_cream.jpg',
              price: 270,
              Rating: '4',
              time:0,
            },
            {
              Dish_id: 7,
              plate: 'Cream Caramel Ice Cream',
              desc:"Simple and elegant, our salted caramel ice cream might just be your new favorite flavor. This is an incredible dessert on its own but can be served alongside some of your favorite holiday desserts like apple or pumpkin pie.",
              imgP: 'assets/image/desserts/cream caramel ice cream.jpg',
              price: 280,
              Rating: '4',
              time:0,
            },
            {
              Dish_id: 8,
              plate: 'Choco Brownie Fudge',
              desc:"A chocolate brownie or simply a brownie is a chocolate baked confection. Brownies come in a variety of forms and may be either fudgy or cakey, depending on their density.",
              imgP: 'assets/image/desserts/chocolate fudge brownie.jpg',
              price: 330,
              Rating: '4',
              time:0,
            },
            {
              Dish_id: 9,
              plate: 'Blueberry Cheese Cake Sundae',
              desc:"This rich, velvety, and luscious cheesecake is studded with blueberries that burst with sweetness in every bite. It’s a silky-smooth dessert that sits atop a crunchy graham cracker crust and right before serving, you smother it with an elegant blueberry sauce.",
              imgP: 'assets/image/desserts/blueberry_sundae.webp',
              price: 290,
              Rating: '4.1',
              time:0,
            },
            {
              Dish_id: 10,
              plate: 'Oreo Ice Cream',
              desc:"This blueberry oreo ice cream recipe is the perfect way to cool down this summer. It's an easy no-churn recipe that you can actually scoop right out of the freezer. It's creamy, smooth, and bursting with flavor",
              imgP: 'assets/image/desserts/oreo_icecream.jpg',
              price: 300,
              Rating: '5',
              time:0,
            },
          ],
        },
      ],
    },
    {
      id: 4,
      Dish_Type: 'Mocktail And Mojito',
      Image: 'assets/image/dishImage/main mojito.jpg',
      Desc: 'The mojito is such a classic drink. The fresh mint, the tangy lime juice and the touch of sweetness makes for a perfect drink',
      Sub: [
        {
          sub_id: 1,
          sub_category: 'Mocktail',
          desc: 'Ten Types',
          imgC: 'assets/image/dishImage/main mojito.jpg',
          sub1: [
            {
              Dish_id: 1,
              plate: 'Green Apple',
              desc:" Green Apple Mojito is prepared with white rum, green apple syrup, lemon juice, soda and mint leaves; and is an apt drink for a summer party. The addition of white rum in the recipe, elevates the flavours of the drink and makes it even more enticing in taste.",
              imgP: 'assets/image/Mocktail and Mojito/green_apple.webp',
              price: 170,
              Rating: '5',
              time:0,
            },
            {
              Dish_id: 2,
              plate: 'Pineapple',
              desc:"The Pineapple Mojito! The classic Mojito is one of our top greatest cocktails of all time: bubbly, minty, and artfully simple. Add tropical pineapple to the mix, and it’s a symphony of flavor! The sweet tart of the fruit balances the tangy lime and sweet cooling mint perfectly.",
              imgP: 'assets/image/Mocktail and Mojito/pineapple-mojito.jpg',
              price: 160,
              Rating: '4.6',
              time:0,
            },
            {
              Dish_id: 3,
              plate: 'Classic Mint',
              desc:"A classic cocktail that originated in Cuba, the mojito is a favorite summertime beverage worldwide. The mint and lime give it a cool, refreshing flavor, and the soda lightens it up with a fizzy crispness.",
              imgP: 'assets/image/Mocktail and Mojito/Classic Mint.jpg',
              price: 150,
              Rating: '4',
              time:0,
            },
            {
              Dish_id: 4,
              plate: 'Mango',
              desc:"This mango cocktail is made much like any mojito: Fresh mint and lime are muddled with a sweetener and topped with rum, ice, and soda. In this case, honey works out very well, and the richer taste marries the tropical fruit and mint to the rum wonderfully.",
              imgP: 'assets/image/Mocktail and Mojito/mango-mojito.webp',
              price: 160,
              Rating: '4.2',
              time:0,
            },
            {
              Dish_id: 5,
              plate: 'Water Melon',
              desc:"Is there anything more summery than a fresh, juicy watermelon? This mojito is perfect for summertime parties, BBQs, birthdays, and girls' nights. It's refreshing, delicious, and super easy to make on a hot day.",
              imgP: 'assets/image/Mocktail and Mojito/watermelon_mojito.webp',
              price: 170,
              Rating: '4.3',
              time:0,
            },
            {
              Dish_id: 6,
              plate: 'Strawberry Mojito',
              desc:"This Strawberry Mojito is the perfect summer spin on a classic! When strawberries are at their peak, their sweetness (and pretty color!) offer a delightful twist on the traditional mojito.",
              imgP: 'assets/image/Mocktail and Mojito/strawberry-mojito.webp',
              price: 160,
              Rating: '4',
              time:0,
            },
            {
              Dish_id: 7,
              plate: 'BlackBerry Mojito',
              desc:"The blackberry mojito is a fruity spin on the Mojito: a classic cocktail invented in Havana, Cuba. The modern version of the drink was invented in the 1930’s, though its origins stem back hundreds of years.",
              imgP: 'assets/image/Mocktail and Mojito/blackberry_mojito.webp',
              price: 160,
              Rating: '5',
              time:0,
            },
            {
              Dish_id: 8,
              plate: 'Blue Lagoon',
              desc:"Tall, refreshing and bluer than the bluest Caribbean sky, the cocktail turns vodka, blue curaçao and lemonade into a drink you’ll want to dive into.",
              imgP: 'assets/image/Mocktail and Mojito/Blue-Lagoon.webp',
              price: 170,
              Rating: '5',
              time:0,
            },
            {
              Dish_id: 9,
              plate: 'CocoJito',
              desc:"A yummy frozen mojito with a slight coconut sweetness. Add more cream of coconut for a sweeter drink. Add more rum for a stronger one! Enjoy!",
              imgP: 'assets/image/Mocktail and Mojito/cocojito.jpg',
              price: 160,
              Rating: '4',
              time:0,
            },
            {
              Dish_id: 10,
              plate: 'Ginger Lime',
              desc:"Ginger Lime Mojito recipe is sparkly, cool and refreshing, the flavors of mint, lime and ginger meld together perfectly with a dark aged rum. The flavors of the mint and lime are intensified by muddling and the ginger adds a perfect sharpness to the mix.",
              imgP: 'assets/image/Mocktail and Mojito/ginger_lime.jpg',
              price: 150,
              Rating: '4',
              time:0,
            },
          ],
        },
      ],
    },
  ];
}
